unbind r
bind r source-file ~/.tmux.conf

set -g mouse on
set-option -g status-position top
set -g status on
set -g status-bg "#4F4F4F"
set -g status-fg "#DFDFDF"
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

