unbind r
bind r source-file ~/.tmux.conf

set -g mouse on
set-option -g status-position top
set -g status on
set -g default-terminal "tmux-256color"
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'

set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "basic"
run '~/.tmux/plugins/tpm/tpm'
